-- Disable safe update mode temporarily
SET SQL_SAFE_UPDATES = 0;

-- Create tasks table
CREATE TABLE IF NOT EXISTS student_tasks (
    task_id INT AUTO_INCREMENT PRIMARY KEY,
    chef_id INT NOT NULL,
    blok VARCHAR(100) NOT NULL,
    onderdeel VARCHAR(255) NOT NULL,
    techniek VARCHAR(255) NOT NULL,
    taak TEXT NOT NULL,
    uitgevoerd_op DATE,
    opmerkingen TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (chef_id) REFERENCES chefs(chef_id) ON DELETE CASCADE
);

-- Create a table to store the trigger template
CREATE TABLE IF NOT EXISTS task_trigger_template (
    template_id INT AUTO_INCREMENT PRIMARY KEY,
    is_default BOOLEAN DEFAULT FALSE,
    trigger_name VARCHAR(100) NOT NULL,
    trigger_sql TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Clear any existing default templates to avoid duplicates
DELETE FROM task_trigger_template WHERE is_default = TRUE;

-- Insert updated default trigger template with proper syntax
INSERT INTO task_trigger_template (is_default, trigger_name, trigger_sql) VALUES 
(TRUE, 'default_task_template', 
'INSERT INTO student_tasks (chef_id, blok, onderdeel, techniek, taak) VALUES 
(:chef_id, "Leerjaar 1 P1", "Persoonlijke Hygiëne", "Keukentechniek", "Handen wassen"),
(:chef_id, "Leerjaar 1 P1", "Persoonlijke Hygiëne", "Keukentechniek", "Werkplek schoonmaken"),
(:chef_id, "Leerjaar 1 P1", "Persoonlijke Hygiëne", "Keukentechniek", "Afval verwijderen"),
(:chef_id, "Leerjaar 1 P1", "Persoonlijke Hygiëne", "Keukentechniek", "Debarrasseren van keukenmateriaal"),
(:chef_id, "Leerjaar 1 P1", "Schoonmaaktechnieken", "Keukentechniek", "Schoonmaken/schillen"),
(:chef_id, "Leerjaar 1 P1", "Schoonmaaktechnieken", "Keukentechniek", "Wassen"),
(:chef_id, "Leerjaar 1 P1", "Schoonmaaktechnieken", "Kooktechniek", "Pellen"),
(:chef_id, "Leerjaar 1 P1", "Schoonmaaktechnieken", "Kooktechniek", "Ontvellen"),
(:chef_id, "Leerjaar 1 P1", "Schoonmaaktechnieken", "Kooktechniek", "Uitboren"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Snijden"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Tourneren"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Hakken"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Uitsnijden"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Schaven"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Plukken"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Cutteren"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Ciseleren"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Raspen"),
(:chef_id, "Leerjaar 1 P1", "Opdeeltechnieken", "Kooktechniek", "Uitboren"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "(Op)kloppen"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Spatelen"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Mengen"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Paneren"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Doorwrijven"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Fijnmalen"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "(Af)meten"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Ontdooien"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Vacumeren"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Passeren"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Pureren"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "Canneleren"),
(:chef_id, "Leerjaar 1 P2", "Koude voorbewerkingen", "Kooktechniek", "(Op)spuiten"),
(:chef_id, "Leerjaar 1 P2", "Schoonmaakplan", "Keukentechniek", "Bespreken schoonmaakplan met leermeester"),
(:chef_id, "Leerjaar 1 P2", "Schoonmaakplan", "Keukentechniek", "Schoonmaken van werkruimtes"),
(:chef_id, "Leerjaar 1 P2", "Schoonmaakplan", "Keukentechniek", "Schoonmaken van gereedschappen"),
(:chef_id, "Leerjaar 1 P2", "Schoonmaakplan", "Keukentechniek", "Schoonmaken van machines"),
(:chef_id, "Leerjaar 1 P2", "Schoonmaakplan", "Keukentechniek", "Datum controle en registratie"),
(:chef_id, "Leerjaar 1 P3", "Warme voorbewerkingen", "Kooktechniek", "Aanfruiten"),
(:chef_id, "Leerjaar 1 P3", "Warme voorbewerkingen", "Kooktechniek", "Aanzweten"),
(:chef_id, "Leerjaar 1 P3", "Warme voorbewerkingen", "Kooktechniek", "Myoteren"),
(:chef_id, "Leerjaar 1 P3", "Warme voorbewerkingen", "Kooktechniek", "Ontzuren"),
(:chef_id, "Leerjaar 1 P3", "Warme voorbewerkingen", "Kooktechniek", "Bruneren"),
(:chef_id, "Leerjaar 1 P3", "Warme voorbewerkingen", "Kooktechniek", "Lieren"),
(:chef_id, "Leerjaar 1 P3", "Bereidingstechnieken", "Kooktechniek", "Blancheren"),
(:chef_id, "Leerjaar 1 P3", "Bereidingstechnieken", "Kooktechniek", "Bakken"),
(:chef_id, "Leerjaar 1 P3", "Bereidingstechnieken", "Kooktechniek", "Grillen"),
(:chef_id, "Leerjaar 1 P3", "Bereidingstechnieken", "Kooktechniek", "Frituren"),
(:chef_id, "Leerjaar 1 P3", "Werkt gerechten voor de uitgifte af", "Kooktechniek", "Opmaken en garneren van koude voorgerechten"),
(:chef_id, "Leerjaar 1 P3", "Werkt gerechten voor de uitgifte af", "Kooktechniek", "Opmaken en garneren van nagerechten"),
(:chef_id, "Leerjaar 1 P3", "Beheert de keukenvoorraden", "Keukentechniek", "Controleren van de afleverbon"),
(:chef_id, "Leerjaar 1 P3", "Beheert de keukenvoorraden", "Keukentechniek", "Temperatuurcontrole en registratie"),
(:chef_id, "Leerjaar 1 P3", "Beheert de keukenvoorraden", "Keukentechniek", "Gewichtscontrole en registratie"),
(:chef_id, "Leerjaar 1 P3", "Beheert de keukenvoorraden", "Keukentechniek", "Datum controle en registratie"),
(:chef_id, "Leerjaar 1 P4", "Warme voorbewerkingen", "Kooktechniek", "Afschuimen"),
(:chef_id, "Leerjaar 1 P4", "Warme voorbewerkingen", "Kooktechniek", "Ontvetten"),
(:chef_id, "Leerjaar 1 P4", "Warme voorbewerkingen", "Kooktechniek", "Monteren"),
(:chef_id, "Leerjaar 1 P4", "Warme voorbewerkingen", "Kooktechniek", "Pinceren"),
(:chef_id, "Leerjaar 1 P4", "Warme voorbewerkingen", "Kooktechniek", "Arroseren"),
(:chef_id, "Leerjaar 1 P4", "Bereidingstechnieken", "Kooktechniek", "Braden"),
(:chef_id, "Leerjaar 1 P4", "Bereidingstechnieken", "Kooktechniek", "Gratineren"),
(:chef_id, "Leerjaar 1 P4", "Bereidingstechnieken", "Kooktechniek", "Rissoleren"),
(:chef_id, "Leerjaar 1 P4", "Bereidingstechnieken", "Kooktechniek", "Pocheren"),
(:chef_id, "Leerjaar 1 P4", "Bereidingstechnieken", "Kooktechniek", "Stoven"),
(:chef_id, "Leerjaar 1 P4", "Bereidingstechnieken", "Kooktechniek", "Regenereren"),
(:chef_id, "Leerjaar 1 P4", "Bereidingstechnieken", "Kooktechniek", "Roerbakken"),
(:chef_id, "Leerjaar 1 P4", "Slaat de geleverde producten op", "Keukentechniek", "Opslaan van de in ontvangst genomen goederen"),
(:chef_id, "Leerjaar 1 P4", "Slaat de geleverde producten op", "Keukentechniek", "Uit- en/of ompakken van grondstoffen en producten"),
(:chef_id, "Leerjaar 1 P4", "Slaat de geleverde producten op", "Keukentechniek", "Controleren en zorgen voor de juiste bewaarcondities in de opslagruimtes"),
(:chef_id, "Leerjaar 1 P4", "Slaat de geleverde producten op", "Keukentechniek", "Hanteren van het principe van \"first in, first out\" bij de opslag van grondstoffen en producten"),
(:chef_id, "Leerjaar 1 P4", "Slaat de geleverde producten op", "Keukentechniek", "Opvolgen van de HACCP-richtlijnen bij het opslaan van grondstoffen en producten"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Marineren"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Bereiden van azijnsauzen"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Bereiden van oliesauzen"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Bereiden van koude sauzen"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Toepassen van koude bindingen"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Toepassen van warme bindingen"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Maken van groentebouillon"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Bereiden van aardappelspijzen"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Braiseren"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Bereiden van rijstspijzen"),
(:chef_id, "Leerjaar 2 P5", "Bereidingstechnieken", "Kooktechniek", "Maken van een beslag"),
(:chef_id, "Leerjaar 2 P5", "Werkt gerechten voor de uitgifte af ", "Kooktechniek", "Opmaken en garneren van warme voorgerechten"),
(:chef_id, "Leerjaar 2 P5", "Werkt gerechten voor de uitgifte af ", "Kooktechniek", "Opmaken en garneren van hoofdgerechten"),
(:chef_id, "Leerjaar 2 P5", "Plant zijn werkzaamheden ", "Keukentechniek", "Inventariseren van werkzaamheden (MEP lijst)"),
(:chef_id, "Leerjaar 2 P5", "Plant zijn werkzaamheden ", "Keukentechniek", "Opstellen werkplanning met schatting van benodigde tijd"),
(:chef_id, "Leerjaar 2 P5", "Plant zijn werkzaamheden ", "Keukentechniek", "Werkplanning met inschatting van tijd bespreken met de leidinggevende"),
(:chef_id, "Leerjaar 2 P6", "Past recepten aan", "Keukentechniek", "Vastleggen van een receptuur"),
(:chef_id, "Leerjaar 2 P6", "Past recepten aan", "Keukentechniek", "Aanpassen van recepten"),
(:chef_id, "Leerjaar 2 P6", "Bereidingstechnieken", "Kooktechniek", "Bereiden van bavaroise"),
(:chef_id, "Leerjaar 2 P6", "Bereidingstechnieken", "Kooktechniek", "Maken van een deeg product"),
(:chef_id, "Leerjaar 2 P6", "Bereidingstechnieken", "Kooktechniek", "Bereiden van meelspijzen"),
(:chef_id, "Leerjaar 2 P6", "Bereidingstechnieken", "Kooktechniek", "Maken van visbouillon"),
(:chef_id, "Leerjaar 2 P6", "Bereidingstechnieken", "Kooktechniek", "Maken van runderbouillon"),
(:chef_id, "Leerjaar 2 P6", "Bestelt benodigde producten", "Keukentechniek", "Vastleggen algemene bestelprocedure leerbedrijf"),
(:chef_id, "Leerjaar 2 P6", "Bestelt benodigde producten", "Keukentechniek", "Controleren van de voorraad en vaststellen tekorten"),
(:chef_id, "Leerjaar 2 P6", "Bestelt benodigde producten", "Keukentechniek", "Maken van een bestelling aan de hand van bestelmethoden van het leerbedrijf"),
(:chef_id, "Leerjaar 2 P6", "Controleert producten en voert keukenadministratie uit ", "Keukentechniek", "Labellen van bereide producten"),
(:chef_id, "Leerjaar 2 P6", "Controleert producten en voert keukenadministratie uit ", "Keukentechniek", "Controleren van bereide producten"),
(:chef_id, "Leerjaar 2 P6", "Controleert producten en voert keukenadministratie uit ", "Keukentechniek", "Uitvoeren keukenadministratie"),
(:chef_id, "Leerjaar 2 P6", "Verricht onderhoud aan keukeninventaris", "Keukentechniek", "Preventief onderhoud van keukeninventaris"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Keukentechniek", "Opstellen recepturen van de 3 gerecht"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Keukentechniek", "Opstellen bestellijst 3-gangenmenu"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Keukentechniek", "Opstellen mise en place lijst en werkplanning"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Keukentechniek", "Ontvangen en opslaan bestelde producten"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Kooktechniek", "Uitvoeren voorbereidende werkzaamheden voor het menu (MEP)"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Kooktechniek", "Bereiden van de gerechten"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Kooktechniek", "Afwerken van de gerechten voordoorgifte"),
(:chef_id, "Leerjaar 2 P7", "Opdracht: Stel een 3 gangenmenu op samen met je leermeester", "Keukentechniek", "Nabespreken van de uitgevoerde opdracht met de leermeester.")'
);

-- Re-enable safe update mode
SET SQL_SAFE_UPDATES = 1;
